name: Release PDF

on:
  pull_request:
    branches: [main]
    paths: 'docs/README.md'
  workflow_dispatch:

jobs:
  build:
    name: Release PDF
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install

      - name: Install packages
        run: |
          sudo apt-get install -y chromium-browser
          
          sudo apt-get install -y libatk1.0-0
          sudo apt-get install -y libatk-bridge2.0-0
          sudo apt-get install -y libcups2
          sudo apt-get install -y libxkbcommon0
          sudo apt-get install -y libxcomposite-dev
          sudo apt-get install -y libxdamage1
          sudo apt-get install -y libxrandr2
          sudo apt-get install -y libgbm-dev
          sudo apt-get install -y libpangocairo-1.0-0
          sudo apt-get install -y libasound2

      - name: Build pdf
        run: yarn build:pdf
      
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false