name: Generate Release PDF

on:
  pull_request:
    branches: [main]
    paths: 'docs/README.md'
  workflow_dispatch:

jobs:
  build:
    name: Generate Release PDF
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install

      - name: Install Packages
        run: |
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y libatk1.0-0
          sudo apt-get install -y libatk-bridge2.0-0
          sudo apt-get install -y libcups2
          sudo apt-get install -y libxkbcommon0
          sudo apt-get install -y libxcomposite-dev
          sudo apt-get install -y libxdamage1
          sudo apt-get install -y libxrandr2
          sudo apt-get install -y libgbm-dev
          sudo apt-get install -y libpangocairo-1.0-0
          sudo apt-get install -y libasound2
      
      - name: Generate PDF
        run: yarn generate:pdf
      
      - name: Generate TAG_NAME
        run: |
          export TAG_NAME=$(TZ=Asia/Tokyo date +%Y.%m.%d.%H%M)
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      
      - name: Generate release note
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          files: docs/README.pdf